name: RunTests

on: [push]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Container
        uses: addnab/docker-run-action@v3
        with:
          image: postman/newman:latest
          options: -v ${{ github.workspace }}/collections:/etc/newman
          run: run "storage_service_collection.json" --reporters="cli"
